"""Generate MAP.md — a human/AI-readable overview of the catalogued corpus.

Answers "what do I have", which full-text search structurally cannot.
Regenerate any time; it is derived entirely from the catalogue.

Intentionally ONE file, written next to the DB (outside any synced tree).
Per-folder intent lines are a separate, hand-annotated artefact — see
cards.py. Per-folder index files inside the corpus itself were considered
and rejected: they go stale immediately and mutating text inside a
cloud-synced tree thrashes sync.
"""

from __future__ import annotations

import sqlite3
from collections import defaultdict
from pathlib import Path

from .config import Config

# A subtree needs at least this many files to get its own section.
SUBTREE_MIN = 40
# Facet values listed per subtree.
TOP_FACETS = 5


def human_bytes(n):
    if not n:
        return "0"
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.0f}{unit}" if unit == "B" else f"{n:.1f}{unit}"
        n /= 1024


def subtree_of(path, root):
    """Second path component, i.e. root/<this>. '(loose)' for files at root."""
    rest = path[len(root) + 1:] if path.startswith(root + "/") else ""
    if "/" not in rest:
        return "(loose files)"
    return rest.split("/", 1)[0]


def top_n(counter, n=TOP_FACETS):
    items = [(k or "—", v) for k, v in counter.items()]
    items.sort(key=lambda kv: -kv[1])
    return ", ".join(f"{k} {v}" for k, v in items[:n])


def generate(cfg: Config) -> str:
    con = sqlite3.connect(f"file:{cfg.db}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    try:
        rows = con.execute(
            """
            SELECT path, root, bytes, doc_type, context_type, rights,
                   confidential, authored_date, client
            FROM files
            """
        ).fetchall()

        total_files = len(rows)
        total_bytes = sum(r["bytes"] or 0 for r in rows)

        # root -> subtree -> aggregates
        tree = defaultdict(lambda: defaultdict(lambda: {
            "n": 0, "bytes": 0,
            "doc": defaultdict(int), "ctx": defaultdict(int),
            "clients": defaultdict(int),
            "own_open": 0, "restricted": 0,
            "years": [],
        }))

        for r in rows:
            root = r["root"] or "(none)"
            sub = subtree_of(r["path"], root)
            a = tree[root][sub]
            a["n"] += 1
            a["bytes"] += r["bytes"] or 0
            a["doc"][r["doc_type"]] += 1
            a["ctx"][r["context_type"]] += 1
            if r["client"]:
                a["clients"][r["client"]] += 1
            if r["rights"] == "OWN" and not r["confidential"]:
                a["own_open"] += 1
            if r["rights"] == "RESTRICTED":
                a["restricted"] += 1
            if r["authored_date"]:
                a["years"].append(r["authored_date"][:4])

        out = []
        w = out.append

        w("# Documents map")
        w("")
        w("> Generated by `shelfmark map` from the catalogue. **Do not "
          "hand-edit** — regenerate instead. Hand-written intent lines live "
          "in FOLDER_CARDS.md.")
        w("")
        w(f"**{total_files:,} files · {human_bytes(total_bytes)} · "
          f"{len(tree)} roots**")
        w("")

        # ---- roots summary table ---------------------------------------
        w("## Roots")
        w("")
        w("| root | files | size | own+shareable | restricted |")
        w("|---|--:|--:|--:|--:|")
        root_order = sorted(tree.items(),
                            key=lambda kv: -sum(a["n"] for a in kv[1].values()))
        for root, subs in root_order:
            n = sum(a["n"] for a in subs.values())
            b = sum(a["bytes"] for a in subs.values())
            own = sum(a["own_open"] for a in subs.values())
            res = sum(a["restricted"] for a in subs.values())
            w(f"| `{root}` | {n:,} | {human_bytes(b)} | {own:,} | {res:,} |")
        w("")

        # ---- per-root subtree detail ------------------------------------
        for root, subs in root_order:
            root_n = sum(a["n"] for a in subs.values())
            w(f"## `{root}` — {root_n:,} files")
            w("")
            listed = sorted(subs.items(), key=lambda kv: -kv[1]["n"])
            shown = [(s, a) for s, a in listed if a["n"] >= SUBTREE_MIN]
            hidden = [(s, a) for s, a in listed if a["n"] < SUBTREE_MIN]

            if shown:
                w("| subtree | files | size | is (doc_type) | for (context_type) | authored |")
                w("|---|--:|--:|---|---|---|")
                for sub, a in shown:
                    years = sorted(a["years"])
                    span = f"{years[0]}–{years[-1]}" if years else "—"
                    w(f"| `{sub}` | {a['n']:,} | {human_bytes(a['bytes'])} | "
                      f"{top_n(a['doc'], 3)} | {top_n(a['ctx'], 3)} | {span} |")
                w("")
            if hidden:
                hn = sum(a["n"] for _, a in hidden)
                names = ", ".join(f"`{s}`" for s, _ in hidden[:25])
                more = f" … +{len(hidden) - 25} more" if len(hidden) > 25 else ""
                w(f"<sub>{len(hidden)} smaller subtrees ({hn:,} files): "
                  f"{names}{more}</sub>")
                w("")

        # ---- where the reusable material actually is ---------------------
        w("## Where the shareable IP is")
        w("")
        w("`rights=OWN AND confidential=0` — the practice-library shortlist.")
        w("")
        w("| folder | files |")
        w("|---|--:|")
        ip = con.execute(
            """
            SELECT root, count(*) n FROM files
            WHERE rights='OWN' AND confidential=0
            GROUP BY root ORDER BY n DESC
            """
        ).fetchall()
        for r in ip:
            w(f"| `{r['root']}` | {r['n']:,} |")
        w("")

        # ---- things a human should look at -------------------------------
        w("## Needs a human")
        w("")
        unknown = con.execute(
            "SELECT count(*) c FROM files WHERE rights='UNKNOWN'").fetchone()["c"]
        dupes = con.execute(
            """SELECT count(*) c FROM (SELECT sha256 FROM files
               WHERE sha256 IS NOT NULL AND sha256 != ''
               GROUP BY sha256 HAVING count(*) > 1)"""
        ).fetchone()["c"]
        noctx = con.execute(
            "SELECT count(*) c FROM files WHERE context_type IS NULL OR context_type=''"
        ).fetchone()["c"]
        w(f"- {unknown:,} files still `rights=UNKNOWN`")
        w(f"- {dupes:,} sha256 groups with duplicates")
        w(f"- {noctx:,} files with no `context_type` (folder purpose unclassified)")
        w("")

        return "\n".join(out) + "\n"
    finally:
        con.close()


def write(cfg: Config, out_path: Path | None = None,
          to_stdout: bool = False) -> str:
    text = generate(cfg)
    if to_stdout:
        return text
    dest = out_path or cfg.db.parent / "MAP.md"
    dest.write_text(text)
    return f"wrote {dest} ({len(text):,} chars)"
